version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:9999
    volumes:
      - .:/code
    ports:
      - "9999:9999"
    depends_on:
        - db
  db:
      image: postgres:11
      environment:
          - "POSTGRES_HOST_AUTH_METHOD=trust"