# Generated by Django 3.1.2 on 2020-10-18 23:48

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(default=django.contrib.auth.models.User, max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.CharField(blank=True, max_length=64, null=True)),
                ('type', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('size', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('pets', models.BooleanField(default=False)),
                ('breakfast', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('extras', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('main_image', models.URLField(blank=True, null=True)),
                ('image1', models.URLField(blank=True, null=True)),
                ('image2', models.URLField(blank=True, null=True)),
                ('image3', models.URLField(blank=True, null=True)),
                ('auth', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
