# Generated by Django 3.1.2 on 2020-10-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fav',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fav',
            name='slug',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
