# Generated by Django 3.1.2 on 2020-10-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.IntegerField()),
                ('size', models.IntegerField()),
                ('price', models.IntegerField()),
                ('extras', models.TextField(blank=True)),
                ('breakfast', models.CharField(max_length=5)),
                ('pets', models.CharField(max_length=5)),
                ('images', models.TextField()),
                ('hotelName', models.CharField(max_length=64)),
                ('published_at', models.CharField(max_length=64)),
            ],
        ),
    ]
