# Generated by Django 3.1.2 on 2020-10-17 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_api', '0002_auto_20201017_0555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='images',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='postimages',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='hotels_api.room'),
        ),
    ]
